<?php

namespace Layer\Manager;


class ManagerPeoples extends Manager{
    private $dbh;
    public function __construct($dbh)
    {
        $this->dbh = $dbh;
    }
    public function insert($entity)
    {
        $table[] = ['first-name'=>$entity->getFirstName(), 'second-name'=>$entity->getSecondName()];
        $sth = $this->dbh->prepare('INSERT INTO Peoples VALUES (:firstname,:lastname)');
        $sth->execute(array(':firstname' => $table['first-name'], ':lastname' => $table['second-name']));
    }

    public function update($entity)
    {
        parent::update($entity); // TODO: Change the autogenerated stub
    }

    public function remove($entity)
    {
        parent::remove($entity); // TODO: Change the autogenerated stub
    }

    public function find($entityName, $id)
    {
        parent::find($entityName, $id); // TODO: Change the autogenerated stub
    }

    public function findAll($entityName)
    {
        parent::findAll($entityName); // TODO: Change the autogenerated stub
    }

    public function findBy($entityName, $criteria = [])
    {
        parent::findBy($entityName, $criteria); // TODO: Change the autogenerated stub
    }

}